"""remove tmid

Revision ID: de8ae49caf8a
Revises: d99900ae34df
Create Date: 2024-05-20 13:55:46.531760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8ae49caf8a'
down_revision = 'd99900ae34df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('tm_id')
        batch_op.drop_column('mbid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tm_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
